### ISSUE TITLE
Unterstützung für Tastaturevents

### ISSUE THREAD

**Issue by johann-lr** [L3P3/prog#5]
Es wäre für einen Nutzer angenehm, wenn die App sich mit einigen Tasten steuern ließe.
Beispiele hierfür sind ein ESC-Tastendruck, um Menüs und Popups zu schließen oder Pfeiltasten, um zwischen Untermenüs zu navigieren (Liste hier ist ja beliebig erweiterbar :)).

**Comment by L3P3** [comment]
Auf Pfeiltasten habe ich gerade keine Lust.
