### ISSUE TITLE
Design der Tabellen optimieren

### ISSUE THREAD

**Issue by johann-lr** [L3P3/prog#7]
* Inhalt wirkt sehr gequetscht: Padding der Tabellenzellen erhöhen
* Border-Radius von 5px auf die oberen beiden Ecken der Tabelle setzen
* Sliderelemente der Tabellenspalten dünner einstellen (1px?)

**Comment by L3P3** [comment]
Die Kombination aus einer runden Ecke (lol) und einem 1px-Rand sieht nicht so schön aus.
